# Generated by Django 4.2.7 on 2024-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_latitude_area_longitude_alter_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pictures',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
